### ISSUE TITLE
Package ‘org-capture-0’ is unavailable

### ISSUE THREAD

**Issue by czqhurricnae** [vascoferreira25/org-mode-incremental-reading#10]
Try to install package in Spacemacs but throw an error:
```
(Spacemacs) Error: 
An error occurred while installing incremental-reading (error: (error Package ‘org-capture-0’ is unavailable))
```
And try to remove `org-protocol` require, then `ox-html` error show:
```
(Spacemacs) Error: 
An error occurred while installing incremental-reading (error: (error Package ‘ox-html-0’ is unavailable))
```

Maybe requires:

```
;; Package-Requires: ((org) (org-protocol) (ox-html) (anki-editor "0.3.3") (request "0.3.0") (emacs "26.6"))
```
should not contain `org-protocol` and `ox-html`, due to these two packages are build in Org now.

**Comment by vascoferreira25** [comment]
Hi! Thank you for helping in improving this package. As you didn't submit any commit I've added your name to the readme and the source.
