### ISSUE TITLE
Consider adding `incremental-reading-mode-hook`

### ISSUE THREAD

**Issue by czqhurricnae** [vascoferreira25/org-mode-incremental-reading#11]
Use `define-minor-mode` to implement `incremental-reading-mode-hook`.
```
;;;###autoload
(define-minor-mode incremental-reading-mode
  "incremental-reading-mode"
  :lighter " incremental-reading")
```
So now package can be easy to config by:
```
(add-hook 'org-mode-hook #'incremental-reading-mode)
(add-hook 'incremental-reading-mode-hook #'anki-editor-mode)

```
and the org file is opened, `incremental-reading-mode` is activated automatically, then, `incremental-reading-mode-hook` activate `anki-editor-mode`.

Do not need to activate `anki-editor-mode` manually when trying to parse cards and push notes to Anki.

**Comment by vascoferreira25** [comment]
Hi! Thank you for helping in improving this package. As you didn't submit any commit I've added your name to the readme and the source.
