### ISSUE TITLE
Feature request：hide these mess stuff use overlay

### ISSUE THREAD

**Issue by colawithsauce** [vascoferreira25/org-mode-incremental-reading#3]
I am going to take an exam now. after it’s finish at Dec.27, I will have more time to implement this feature. 

Open this issue to remind me.

**Comment by colawithsauce** [comment]
I tried to implement it but still have some problems that need to handle.
This is how it looks:
![hide-properties](https://user-images.githubusercontent.com/51731521/147424673-36c515a6-9f41-48cb-8523-2f2496c8f32e.gif)
You can see that there is only one line that cannot edit it or view it conveniently.

**Comment by colawithsauce** [comment]
Or this is the compact version of it:
![Compact-version](https://user-images.githubusercontent.com/51731521/147424814-ba245546-1f4e-4686-ac82-a0ff31554d52.gif)

**Comment by colawithsauce** [comment]
update: I have solved the issue, it looks like this:
![Hide-v2](https://user-images.githubusercontent.com/51731521/147428672-ffd903ba-c0db-483c-bb6f-9f7987e0bb4c.gif)

**Comment by vascoferreira25** [comment]
This looks amazing!

**Comment by colawithsauce** [comment]
Thanks, I am pleasure that you love it. :smile:

**Comment by vascoferreira25** [comment]
Can this issue be closed as you already submitted a fix to it?

**Comment by colawithsauce** [comment]
ofcourse
