### ISSUE TITLE
Feature request: (optionally) respect the file tag and subtree tag

### ISSUE THREAD

**Issue by colawithsauce** [vascoferreira25/org-mode-incremental-reading#6]
I found it a bit annoying when modifying every note's tag by hand. So it's highly reasonable to add file tags and subtrees tags support.

**Comment by colawithsauce** [comment]
There is two way to implement this feature. 
1. optionally inheriting the tags when creating notes.
2. add tags from its parents when pushing notes.

I think the former one is better.

**Comment by vascoferreira25** [comment]
Couldn't that be done when using the snippet to create cards?

**Comment by vascoferreira25** [comment]
For example, if the notes already have a tag, use that tag in the card, if not, use a previously defined tag.

**Comment by vascoferreira25** [comment]
Would something like this be enough? - It returns the tags of the current heading.

```
#+ATTR_TAGS: `(org-get-tags-string)`
```

Full snippet:

```
# -*- mode: snippet -*-
# name: incremental-reading
# key: <ir-basic
# group: incremental-reading
# --
:ANKI_CARD:
#+ATTR_DECK: ${1:Default}
#+ATTR_TYPE: ${2:Basic}
#+ATTR_TAGS: `(org-get-tags-string)`
#+BEGIN_ANKI org
#+ATTR_FIELD: Front
#+BEGIN_FIELD
${4:Text {{c1::cloze}}}
#+END_FIELD

#+ATTR_FIELD: Back
#+BEGIN_FIELD
${5:Back}
#+END_FIELD
#+END_ANKI
:END:
$0
```

**Comment by vascoferreira25** [comment]
Check the latest commit, I've tried to implement it.

**Comment by colawithsauce** [comment]
It's great!
